name: 🌟 New Enhancement request
description: Request an update to existing component. This is used for changes such as color updates. For new patterns or updated patterns for existing components, use feature request.
title: "<existing component>: <issue title>"
labels: ["type: enhancement", "needs triage"]
body:
- type: textarea
  id: enhancement-description
  attributes:
    label: Description
    description: A description of how the enhancement is intended to work.
  validations:
    required: false
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: |
      Add screenshots of the enhancement/module.
      Tip: You can attach images or log files by pasting or by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: input
  id: figma-link
  attributes:
    label: Figma link
    placeholder: Please paste in the Figma link for the feature/module.
- type: checkboxes
  id: pre-requisites
  attributes:
    label: Engineering pre-requisites
    description: |
      Please verify what you've completed so far.
      **Note: a "successful review" means those teams give their blessing for it to proceed to engineering.**
    options:
      - label: Supports dark mode.
      - label: Supports responsive design.
      - label: Tokens have been provided (or already exist).
