name: 🌟 New Feature request
description: Request a new feature for Skin
title: "<existing/proposed component name>: <issue title>"
labels: ["type: feature", "status: needs triage"]
body:
- type: textarea
  id: feature-description
  attributes:
    label: Description
    description: A description of how the feature/module is intended to work.
  validations:
    required: false
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: |
      Add screenshots of the feature/module.
      Tip: You can attach images or log files by pasting or by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: input
  id: figma-link
  attributes:
    label: Figma link
    placeholder: Please paste in the Figma link for the feature/module.
- type: checkboxes
  id: pre-requisites
  attributes:
    label: Engineering pre-requisites
    description: |
      Please verify what you've completed so far.
      **Note: a "successful review" means those teams give their blessing for it to proceed to engineering.**
    options:
      - label: Successful design review with Design System Team.
      - label: Supports dark mode.
      - label: Supports responsive design.
      - label: Tokens have been provided (or already exist).
      - label: Successful accessibility review with Core A11Y Team.
      - label: Successful frontend review with eBayUI Team.
