#!/usr/bin/env bash
set -e # halt script on error

JEKYLL_ENV=production bundle exec jekyll build --config docs/_config.yml
bundle exec htmlproofer ./_site/index.html --disable-external --empty_alt_ignore --allow_hash_href

# snapshot storybook
# disabled until we get a full license
#bundle exec npx @percy/storybook percy-storybook --widths=320,1280 --build_dir=docs/storybook
