#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build --config docs/_config.yml
bundle exec htmlproofer ./_site/index.html --disable-external --empty_alt_ignore --allow_hash_href

bundle exec npx percy snapshot _site --snapshot-files=index.html,ds6/index.html,test/**/ds4/index.html,test/**/ds6/index.html --ignore-files=test/card,test/dialog
