module.exports = {
    gzip: true,
    multipass: true,
    original: false,
    plugins: [
        'cleanupAttrs',
        'cleanupEnableBackground',
        'cleanupListOfValues',
        'cleanupNumericValues',
        'collapseGroups',
        'convertColors',
        'convertEllipseToCircle',
        'convertPathData',
        'convertShapeToPath',
        'convertStyleToAttrs',
        'convertTransform',
        'inlineStyles',
        'mergePaths',
        'mergeStyles',
        'minifyStyles',
        'moveElemsAttrsToGroup',
        'moveGroupAttrsToElems',
        'removeComments',
        'removeDesc',
        'removeDimensions',
        'removeDoctype',
        'removeEditorsNSData',
        'removeEmptyAttrs',
        'removeEmptyContainers',
        'removeEmptyText',
        'removeHiddenElems',
        'removeMetadata',
        'removeNonInheritableGroupAttrs',
        'removeRasterImages',
        'removeScriptElement',
        'removeStyleElement',
        'removeTitle',
        'removeUnknownsAndDefaults',
        'removeUnusedNS',
        'removeUselessDefs',
        'removeUselessStrokeAndFill',
        'removeViewBox',
        'removeXMLNS',
        'removeXMLProcInst',
        'reusePaths',
        'sortAttrs',
        'sortDefsChildren',
    ],
    pretty: true,
};
